### ISSUE TITLE
템플릿 생성하기

### ISSUE THREAD

**Issue by KimRiun** [valueGa/valueGa_backend#1]
## 💡 Feature Issue

템플릿 생성에 필요한 기능을 개발합니다.

## 🌿  Tasks

- [ ] 종목과 템플릿 종류 request가 요청되면, 응답하는 API router 만들기
- [ ] API 응답에 필요한 데이터 쿼리문(SELECT) 작성하기
- [ ] 쿼리문에 필요한 더미 데이터 넣기
