### ISSUE TITLE
CD yml  추가 작업하기

### ISSUE THREAD

**Issue by subsub97** [valueGa/valueGa_backend#15]
## 💡 Feature Issue

배포후 자 백그라운드에서 서버가  재실행 가능하도록 수정하기

## 🌿  Tasks

- [ ] copy file 경로와  Excute 경로 일치 시키기
- [ ] pm2 script 설정
- [ ] .env 파일 생성 후 값 넣기
