### ISSUE TITLE
Models Create_date 관련 중복 컬럼 수정

### ISSUE THREAD

**Issue by subsub97** [valueGa/valueGa_backend#23]
## 💡 Feature Issue

Sequlize의 Default 속성으로 timestamp가 추가되어 
개별적으로 create_date를 설정한 값을 지우기

## 🌿  Tasks

- [x] user_template_temporary.js
- [x] user_template.js
- [x] value_board.js
