### ISSUE TITLE
종목, 템플릿에 해당하는 3개년 데이터 불러오는 API 만들기

### ISSUE THREAD

**Issue by KimRiun** [valueGa/valueGa_backend#26]
## 💡 Feature Issue

종목, 템플릿에 해당하는 3개년 데이터 불러오는 API 만들기

## 🌿  Tasks

- [x] DB 연결
    - [x] - **ISSUE : DB 연결 안되는 문제 (~11:38)**
    - HostNotFoundError [SequelizeHostNotFoundError]: getaddrinfo ENOTFOUND 3.35.129.99 #localhost
    - process.env.HOST_DOMAIN이 vscode 환경변수에 캐시된 문제
        
        → HOST_DOMAIN을 삭제해도 출력이 가능하다는…이상한 일;;
        
    - HOST_DOMAIN을 HOST으로 이름 변경하고, dotenv에서 .env 파일 경로를 올바르게 수정해서 해결
- [x]  valuation 생성시 DB에서 3개년 가져오는  백엔드 API 만들기
- [x]  valuation 생성시 엑셀 시트에 데이터 뿌려주는 프론트 API 연결하기 (~2:38)
- [x]  템플릿 - 템플릿화 (1열1행만 저장)
    - [x]  PER 템플릿 엑셀 저장하기
    - [x]  템플릿화 백엔드 API 만들고, PER 저장하기
- [x]  템플릿 id로 템플릿 조회하는 API 만들기
- [x] 템플릿화 바이너리 저장 안되고 있던 이슈 해결
- [x]  template_id 에 따라 데이터 구분하기
    - [x]  프론트에서 template_id 같이 보내도록 API 수정
    - [x]  백엔드에서 template_id에 해당하는 template과 FINACE_INFOS를 보내도록 수정
    - [x]  프론트에 template 종류에 따라 컬럼명과 실제 엑셀에 표시될 항목명 (ex. el → 매출액) 매칭되는 enum 정의하기
